/**
 * Agent Execution Context — Phase 9: Specialized Agentic AI Foundation.
 *
 * Defines the execution context passed to every agent's execute() method.
 *
 * The context contains ONLY what the agent needs to do its work:
 *   - Who is asking (user identity — for audit logging only)
 *   - Which organization (for tenant-isolated retrieval)
 *   - What they're asking (query)
 *   - Operational limits (configuration)
 *
 * The context does NOT contain:
 *   - Database credentials
 *   - API keys or secrets
 *   - Other organization data
 *   - Internal infrastructure information
 *   - Raw HTTP request objects
 *
 * Building the context from JWT-verified data (not client body) is the
 * responsibility of AgentExecutionService, NOT individual agents.
 */

// ─── Agent Configuration ──────────────────────────────────────────────────────

/**
 * Operational limits for a single agent execution.
 * Controls cost, performance, and safety boundaries.
 */
export interface AgentConfiguration {
  /**
   * Maximum number of evidence chunks to retrieve for this agent.
   * Agents receive more context than the base RAG query (8 vs 5)
   * to support richer multi-document analysis.
   * Hard maximum: 20 (enforced by RetrievalService).
   */
  maxRetrievalTopK: number;

  /**
   * Maximum tokens the LLM can output in one agent response.
   * Agents produce richer structured output than the base RAG query.
   * Default: 1500 (vs 1024 for base RAG).
   */
  maxOutputTokens: number;

  /**
   * Overall agent execution timeout in milliseconds.
   * If the agent does not complete within this time, AgentTimeoutError is thrown.
   * Default: 45000ms (45 seconds).
   */
  timeoutMs: number;

  /**
   * Timeout for the retrieval step alone (ms).
   * Default: 10000ms (10 seconds).
   */
  retrievalTimeoutMs: number;

  /**
   * Timeout for the LLM call step alone (ms).
   * This is separate from the LLM provider's own timeout.
   * Default: 30000ms (30 seconds).
   */
  llmTimeoutMs: number;
}

/**
 * Default agent configuration applied when no override is provided.
 * All values are intentionally conservative for cost and safety.
 */
export const DEFAULT_AGENT_CONFIGURATION: AgentConfiguration = {
  maxRetrievalTopK: 8,
  maxOutputTokens: 1500,
  timeoutMs: 45_000,
  retrievalTimeoutMs: 10_000,
  llmTimeoutMs: 30_000,
};

// ─── Agent Execution Context ──────────────────────────────────────────────────

/**
 * The execution context provided to every agent's execute() method.
 *
 * This is the agent's complete "view of the world" for a single request.
 * Agents MUST NOT attempt to fetch additional context outside what is here.
 */
export interface AgentExecutionContext {
  /**
   * Unique identifier for this specific request.
   * Sourced from X-Request-ID header or generated by requestIdMiddleware.
   * Used for end-to-end tracing across logs.
   */
  requestId: string;

  /**
   * Correlation ID for linking related agent calls.
   * For Phase 9, equals requestId. In future multi-agent phases,
   * this will be the parent orchestration request ID.
   */
  correlationId: string;

  /**
   * Authenticated user making the request.
   * Included for audit logging within the agent.
   * Agents MUST NOT use user data to filter business evidence —
   * organization-level isolation is the only security boundary.
   */
  user: {
    id: string;
    email: string;
    role: string;
    permissions: string[];
  };

  /**
   * Organization scope for ALL retrieval operations.
   * This is the PRIMARY security boundary.
   * Sourced from verified JWT — never from client body.
   * Every call to RetrievalService MUST use this organizationId.
   */
  organizationId: string;

  /** The user's natural-language business question. */
  query: string;

  /**
   * Optional: restrict retrieval to a specific Knowledge Base.
   * Ownership is validated by AgentExecutionService BEFORE the context is built.
   * If present, the agent can trust this knowledgeBaseId is authorized.
   */
  knowledgeBaseId?: string;

  /**
   * Operational limits for this execution.
   * Agents MUST respect these limits and not exceed them.
   */
  configuration: AgentConfiguration;
}
